minetest.register_node("flolife:stick", {
	description = "Glowstick",
	drawtype = "torchlike",
	tiles = {"flolife_stick_on_floor.png", "flolife_stick_on_ceiling.png", "flolife_stick.png"},
	inventory_image = "flolife_stick.png",
	wield_image = "flolife_stick.png",
	paramtype = "light",
	paramtype2 = "wallmounted",
	sunlight_propagates = true,
	walkable = false,
	light_source = 13,
	selection_box = {
		type = "wallmounted",
		wall_top = {-0.1, 0.5-0.6, -0.1, 0.1, 0.5, 0.1},
		wall_bottom = {-0.1, -0.5, -0.1, 0.1, -0.5+0.6, 0.1},
		wall_side = {-0.5, -0.3, -0.1, -0.5+0.3, 0.3, 0.1},
	},
	groups = {choppy=2,dig_immediate=3,flammable=1,attached_node=1},
	legacy_wallmounted = true,
	sounds = default.node_sound_defaults(),
})
