mobs:register_mob("pyramids:mummy", {
	mob_name = "mummy",
	type = "monster",
	hp_max = 10,
	collisionbox = {-0.4, -0.01, -0.4, 0.4, 1.9, 0.4},
	visual = "mesh",
	mesh = "mobs_mummy.x",
	textures = {"mobs_mummy.png"},
	visual_size = {x=8,y=8},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = .5,
	run_velocity = 2,
	can_climb = false,
	damage = 2,
	drops = {
		{name = "default:papyrus",
		chance = 1,
		min = 3,
		max = 5,},
	},
	light_resistant = true,
	armor = 130,
	drawtype = "front",
	water_damage = 5,
	lava_damage = 10,
	light_damage = 0,
	sounds = {
		random = "mobs_mummy",
	},
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 39,
		walk_start = 41,
		walk_end = 72,
		run_start = 74,
		run_end = 105,
		punch_start = 74,
		punch_end = 105,
	},
})
