-- Aliases to replace PilzAdam's and Jeija's Throwing mods
minetest.register_alias("throwing:arrow_build", "archery:arrow")
minetest.register_alias("throwing:arrow_dig", "archery:arrow")
minetest.register_alias("throwing:arrow_fire", "archery:arrow")
minetest.register_alias("throwing:arrow_teleport", "archery:arrow")
minetest.register_alias("throwing:arrow", "archery:arrow")
minetest.register_alias("throwing:bow_wood", "archery:bow")
minetest.register_alias("throwing:bow_stone", "archery:bow")
minetest.register_alias("throwing:bow_steel", "archery:bow")
minetest.register_alias("throwing:bow", "archery:bow")
